# Generated by Django 3.2.4 on 2021-10-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher', models.CharField(max_length=200)),
                ('student_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
            ],
        ),
    ]
