# Generated by Django 3.2.4 on 2022-01-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classrooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Classrooms.classroom', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Classrooms.classroom', verbose_name='Room'),
        ),
    ]
