# Generated by Django 3.2.4 on 2022-01-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classrooms', '0002_auto_20220123_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classroom_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
