# Generated by Django 3.2.4 on 2022-04-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classrooms', '0007_alter_message_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_id',
            new_name='room_name',
        ),
    ]
