# Generated by Django 3.2.4 on 2022-06-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classrooms', '0012_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='doc',
        ),
        migrations.AddField(
            model_name='announcement',
            name='class_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='')),
                ('rel_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Classrooms.announcement')),
            ],
        ),
    ]
