# Generated by Django 3.2.4 on 2022-06-16 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classrooms', '0013_auto_20220614_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rel_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_post', to='Classrooms.announcement'),
        ),
    ]
