# Generated by Django 3.2.4 on 2022-07-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classrooms', '0014_alter_document_rel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='institutional_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
